import { z } from "zod";

const nullableNumber = z.number().nullable();
const nullableString = z.string().nullable();

export const seasonSchema = z.object({ id: z.number(), year: z.number() });
export const eventSchema = z.object({
  id: z.number(),
  season_id: z.number(),
  round_number: z.number(),
  event_name: z.string(),
  country: nullableString,
  location: nullableString,
  circuit_name: nullableString,
  event_date: nullableString,
  total_laps: nullableNumber,
});
export const sessionSchema = z.object({
  id: z.number(),
  event_id: z.number(),
  session_type: z.string(),
  session_date: nullableString,
  source: z.string(),
  ingestion_status: z.string(),
  ingested_at: nullableString,
  data_version: z.string(),
});
export const driverSchema = z.object({
  id: z.number(),
  driver_number: z.string(),
  abbreviation: z.string(),
  full_name: z.string(),
  team_name: nullableString,
  country_code: nullableString,
  grid_position: nullableNumber,
  finishing_position: nullableNumber,
  status: nullableString,
  points: nullableNumber,
});
export const lapSchema = z.object({
  id: z.number(),
  session_id: z.number(),
  driver_id: z.number(),
  lap_number: z.number(),
  position: nullableNumber,
  lap_time_ms: nullableNumber,
  sector_1_ms: nullableNumber,
  sector_2_ms: nullableNumber,
  sector_3_ms: nullableNumber,
  compound: nullableString,
  tyre_life: nullableNumber,
  stint_number: nullableNumber,
  fresh_tyre: z.boolean().nullable(),
  pit_in: z.boolean(),
  pit_out: z.boolean(),
  track_status: nullableString,
  deleted: z.boolean(),
  inaccurate: z.boolean(),
  timestamp_ms: nullableNumber,
  speed_i1: nullableNumber,
  speed_i2: nullableNumber,
  speed_fl: nullableNumber,
  speed_st: nullableNumber,
  personal_best: z.boolean().nullable(),
});
export const lapPageSchema = z.object({
  items: z.array(lapSchema),
  total: z.number(),
  page: z.number(),
  page_size: z.number(),
});

const pitLossSchema = z.object({
  estimated_ms: z.number(),
  sample_count: z.number(),
  source: z.string(),
  uncertainty_ms: z.number(),
});
const runningOrderSchema = z.object({
  driver_id: z.number(),
  driver_number: z.string(),
  abbreviation: z.string(),
  full_name: z.string(),
  team_name: nullableString,
  position: nullableNumber,
  completed_laps: z.number(),
  compound: nullableString,
  tyre_life: nullableNumber,
  stint_number: nullableNumber,
  last_lap_time_ms: nullableNumber,
  timestamp_ms: nullableNumber.default(null),
  gap_to_leader_ms: nullableNumber,
  gap_to_selected_ms: nullableNumber,
  status: nullableString,
  in_pit: z.boolean().default(false),
});
export const raceStateSchema = z.object({
  session_id: z.number(),
  control_lap: z.number(),
  total_laps: z.number(),
  selected_driver: z.object({
    driver_id: z.number(),
    abbreviation: z.string(),
    full_name: z.string(),
    position: nullableNumber,
    completed_laps: z.number(),
    compound: nullableString,
    tyre_life: nullableNumber,
    tyre_health_percent: nullableNumber.default(null),
    tyre_wear_pct: nullableNumber.default(null),
    tyre_pace_loss_seconds: nullableNumber.default(null),
    tyre_state: nullableString.default(null),
    tyre_performance_life_laps: nullableNumber.default(null),
    tyre_durability_laps: nullableNumber.default(null),
    tyre_stint_sample_count: z.number().default(0),
    tyre_life_source: nullableString.default(null),
    stint_number: nullableNumber,
    last_lap_time_ms: nullableNumber,
    recent_pace_ms: nullableNumber,
    recent_pace_sample_count: z.number(),
    timestamp_ms: nullableNumber.default(null),
    pit_history: z.array(
      z.object({
        lap_number: z.number(),
        pit_entry_time_ms: nullableNumber,
        pit_exit_time_ms: nullableNumber,
        pit_duration_ms: nullableNumber,
      }),
    ),
  }),
  running_order: z.array(runningOrderSchema),
  weather: z
    .object({
      timestamp_ms: z.number(),
      air_temperature: nullableNumber,
      track_temperature: nullableNumber,
      humidity: nullableNumber,
      rainfall: z.boolean().nullable(),
      wind_speed: nullableNumber,
    })
    .nullable(),
  race_control: z.object({
    track_status: nullableString,
    status_label: z.string(),
    latest_messages: z.array(z.string()),
    intervention_start_lap: nullableNumber.default(null),
    boxed_driver_ids: z.array(z.number()).default([]),
  }),
  pit_loss: pitLossSchema,
  likely_rejoin_position: nullableNumber,
  nearby_driver_ids: z.array(z.number()),
  data_quality: z.string(),
});
export const timelineSchema = z.object({
  session_id: z.number(),
  driver_id: z.number(),
  total_laps: z.number(),
  stints: z.array(
    z.object({
      stint_number: z.number(),
      compound: nullableString,
      start_lap: z.number(),
      end_lap: z.number(),
      lap_count: z.number(),
    }),
  ),
  pit_laps: z.array(z.number()),
});
const actualStrategySchema = z.object({
  session_id: z.number(),
  driver_id: z.number(),
  control_lap: z.number(),
  actual_finish: nullableNumber,
  actual_status: nullableString,
  actual_total_time_ms: nullableNumber,
  remaining_stops: z.array(
    z.object({
      pit_lap: z.number(),
      next_compound: nullableString,
      pit_duration_ms: nullableNumber,
    }),
  ),
});
const tyreEstimateSchema = z.object({
  compound: z.string(),
  initial_offset_ms: z.number(),
  degradation_per_lap_ms: z.number(),
  sample_count: z.number(),
  source: z.string(),
  uncertainty_ms: z.number(),
  degradation_uncertainty_per_lap_ms: z.number(),
  performance_life_laps: z.number().default(35),
  durability_laps: z.number().default(49),
  stint_sample_count: z.number().default(0),
  life_source: z.string().default("compound_life_fallback"),
});
const monteCarloSchema = z.object({
  mean_predicted_finish: z.number(),
  median_predicted_finish: z.number(),
  most_likely_finish: z.number(),
  expected_total_time_ms: z.number(),
  median_total_time_ms: z.number(),
  mean_time_vs_deterministic_baseline_ms: z.number(),
  median_time_vs_deterministic_baseline_ms: z.number(),
  win_probability: z.number(),
  podium_probability: z.number(),
  points_probability: z.number(),
  improve_actual_probability: nullableNumber,
  improve_stay_out_probability: z.number(),
  race_time_p05_ms: z.number(),
  race_time_p25_ms: z.number(),
  race_time_p75_ms: z.number(),
  race_time_p95_ms: z.number(),
  finish_position_p05: z.number(),
  finish_position_p95: z.number(),
  likely_rejoin_position: nullableNumber,
  traffic_risk: z.number(),
  degradation_risk: z.number(),
  finish_position_distribution: z.array(
    z.object({
      position: z.number(),
      count: z.number(),
      probability: z.number(),
    }),
  ),
  time_delta_histogram: z.array(
    z.object({
      lower_ms: z.number(),
      upper_ms: z.number(),
      count: z.number(),
      probability: z.number(),
    }),
  ),
  simulation_count: z.number(),
  random_seed: z.number(),
  engine_version: z.string(),
  data_quality: z.string(),
});
export const strategyComparisonSchema = z.object({
  comparison_id: z.number(),
  engine_version: z.string(),
  deterministic: z.boolean(),
  session_id: z.number(),
  driver_id: z.number(),
  control_lap: z.number(),
  pit_loss: pitLossSchema,
  available_compounds: z.array(z.string()),
  outcomes: z.array(
    z.object({
      name: z.string(),
      pit_lap: nullableNumber,
      next_compound: nullableString,
      pace_mode: z.string(),
      predicted_finish: z.number(),
      predicted_total_time_ms: z.number(),
      time_vs_actual_ms: nullableNumber,
      time_vs_baseline_ms: z.number(),
      likely_rejoin_position: nullableNumber,
      traffic_risk: z.number(),
      degradation_risk: z.number(),
      final_tyre_age: z.number(),
      pit_loss_ms: z.number(),
      tyre_estimate: tyreEstimateSchema,
      assumptions: z.array(z.string()),
      projected_laps: z
        .array(
          z.object({
            lap_number: z.number(),
            compound: z.string(),
            tyre_age: z.number(),
            stint_number: z.number().default(1),
            effective_tyre_age: z.number().default(1),
            tyre_health_percent: z.number().default(100),
            tyre_wear_pct: z.number().default(0),
            tyre_pace_loss_seconds: z.number().default(0),
            tyre_state: z.string().default("HEALTHY"),
            lap_time_ms: z.number(),
            cumulative_time_ms: z.number(),
            historical_time_ms: z.number().default(0),
            predicted_position: z.number(),
            pit_stop: z.boolean(),
            dnf: z.boolean().default(false),
            status: nullableString.default(null),
            retirement_reason: nullableString.default(null),
            lap_completed: z.boolean().default(true),
          }),
        )
        .default([]),
      monte_carlo: monteCarloSchema.nullable(),
      dnf: z.boolean().default(false),
      current_tyre_health_pct: z.number().default(100),
      current_tyre_wear_pct: z.number().default(0),
      current_tyre_pace_loss_seconds: z.number().default(0),
      projected_next_lap_health_pct: nullableNumber.default(null),
      projected_next_lap_pace_loss_seconds: nullableNumber.default(null),
      cliff_start_health_pct: z.number().default(50),
      tyre_state: z.string().default("HEALTHY"),
      retirement_reason: nullableString.default(null),
      calibration_source: z.string().default("compound_life_fallback"),
    }),
  ),
  recommendation: z.object({
    strategy_name: z.string(),
    explanation: z.string(),
    primary_advantage: nullableString,
    key_risk: nullableString,
    uncertainty_note: nullableString,
  }),
  actual_strategy: actualStrategySchema,
  disclaimer: z.string(),
  simulation_count: z.number(),
  random_seed: z.number(),
  calculation_time_ms: nullableNumber,
  uncertainty_sources: z.array(
    z.object({
      variable: z.string(),
      source: z.string(),
      sample_count: z.number(),
      scale_ms: z.number(),
      fallback: z.boolean(),
      assumption: z.string(),
    }),
  ),
  assumptions: z.array(z.string()),
});
